[package]
# name = "GameCube-ISO-Assistant"
name = "gamecube-iso-assistant"
version = "0.1.0"
authors = ["Addison Bean <addisonbean@gmail.com>"]

[dependencies]
byteorder = "1"
clap = "2"
tempfile = "2.2.0"
lazy_static = "1.0"
regex = "1"
